#!/bin/bash

time=`ls -t | head -1 | awk '{if ($0 ~ /\.time/) print 1; else print 0;}'`
git add *
git commit -m 'auto commit'
git pull --rebase origin main
if (( $time == 0 )); then
	git push
	rm .time
	touch .time
fi

